[application]
name = "smg-portfolio"
out_dir = "dist"
base_path = "/portfolio/"

[web.app]
title = "smg-portfolio"
base_path = "/portfolio/"

[web.config]
base_path = "/portfolio/"

[web.resource]
style = ["main.css"]
script = []

[web.resource.dev]
script = []